version: 1

formatters:
  simple:
    class: logging.Formatter
    format: "%(asctime)s %(name)s %(levelname)s %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  stream_handler:
    class: logging.StreamHandler
    stream: ext://sys.stderr
    level: DEBUG
    formatter: simple

loggers:
  REPORT:
    level: DEBUG
    propagate: false
    handlers: [stream_handler]

  PIPELINE:
    level: DEBUG
    propagate: false
    handlers: [stream_handler]