input_data_path: "data/raw/heart.csv"
report_data_path: "reports/EDA_report.html"
output_model_path: "models/model.pkl"
output_features_transformer_path: "features_transformer/features_transformer.pkl"
output_metric_path: "models/metrics.json"
splitting_params:
  val_size: 0.2
  random_state: 7
train_params:
  model_type: "RandomForestClassifier"
feature_params:
  categorical_features:
  numerical_features:
    - "OverallQual"
    - "MSSubClass"
    - "OverallCond"
    - "GrLivArea"
    - "GarageCars"
    - "1stFlrSF"
    - "Fireplaces"
    - "BsmtFullBath"
    - "YrSold"
    - "YearRemodAdd"
    - "LotFrontage"
    - "age"
    - "sex"
    - "cp"
    - "trestbps"
    - "chol"
    - "fbs"
    - "restecg"
    - "thalach"
    - "exang"
    - "oldpeak"
    - "slope"
    - "ca"
    - "thal"
  features_to_drop:
  target_col: "target"

